// AUTO-GENERATED by scripts/generate-schema-registry.mjs
// Do not edit manually — add new JSON files to src/schemas/ and rebuild.
import type { Schema } from './types.js';
import schema_0 from './schemas/qiime2-2025.1.json';

const REGISTRY: Record<string, Schema> = {
    '2025.1': schema_0 as unknown as Schema,
};

export const LATEST_VERSION = '2025.1';
export const AVAILABLE_VERSIONS: string[] = Object.keys(REGISTRY);

export function getSchema(version?: string): { schema: Schema; version: string } {
    const v = version ?? LATEST_VERSION;
    if (!(v in REGISTRY)) {
        throw new Error(`Unknown QIIME 2 version "${v}". Available: ${AVAILABLE_VERSIONS.join(', ')}`);
    }
    return { schema: REGISTRY[v], version: v };
}
