name: Update Rachis Schema

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * 0" # Weekly on Sunday midnight

jobs:
    update-schema:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.10"

            - name: Run Moshpit Introspection
              run: |
                  docker run --rm -v ${{ github.workspace }}:/mnt quay.io/qiime2/moshpit:2026.1 \
                    python /mnt/.github/scripts/introspect_plugins.py > moshpit.json
                  docker rmi quay.io/qiime2/moshpit:2026.1

            - name: Run Amplicon Introspection
              run: |
                  docker run --rm -v ${{ github.workspace }}:/mnt quay.io/qiime2/amplicon:2026.1 \
                    python /mnt/.github/scripts/introspect_plugins.py > amplicon.json
                  docker rmi quay.io/qiime2/amplicon:2026.1

            - name: Run Pathogenome Introspection
              continue-on-error: true
              run: |
                  docker run --rm -v ${{ github.workspace }}:/mnt quay.io/qiime2/pathogenome:2026.1 \
                    python /mnt/.github/scripts/introspect_plugins.py > pathogenome.json
                  docker rmi quay.io/qiime2/pathogenome:2026.1

            - name: Merge Schemas
              run: |
                  python .github/scripts/merge_schemas.py src/schema.json moshpit=moshpit.json amplicon=amplicon.json pathogenome=pathogenome.json

            - name: Format JSON Schema
              run: |
                  mv src/schema.json raw_schema.json
                  python -m json.tool raw_schema.json src/schema.json

            - name: Check for changes
              id: git-check
              run: |
                  git diff --exit-code src/schema.json || echo "changes=true" >> $GITHUB_OUTPUT

            - name: Commit and Push
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git add src/schema.json
                  git commit -m "chore: update schema.json from latest Rachis distributions"
                  git push
